/**
 * Theme Engine - Inspired by github-readme-stats
 * Supports URL parameter overrides
 */

export interface Theme {
  bg_color: string
  title_color: string
  text_color: string
  icon_color: string
  border_color: string
  ring_color?: string
  accent_color?: string
}

export const themes: Record<string, Theme> = {
  default: {
    bg_color: 'FEFEFE',
    title_color: '0A0A0A',
    text_color: '434D58',
    icon_color: '0066FF',
    border_color: '0A0A0A',
    ring_color: '0066FF',
    accent_color: 'FF3366',
  },
  dark: {
    bg_color: '0A0A0A',
    title_color: 'FEFEFE',
    text_color: 'C9D1D9',
    icon_color: '00FF88',
    border_color: 'FEFEFE',
    ring_color: '00FF88',
    accent_color: 'FF3366',
  },
  radical: {
    bg_color: '141321',
    title_color: 'FE428E',
    text_color: 'A9FEF7',
    icon_color: 'F8D847',
    border_color: 'FE428E',
    ring_color: 'F8D847',
    accent_color: 'FE428E',
  },
  merko: {
    bg_color: '0A0F0D',
    title_color: '68B587',
    text_color: 'ABD200',
    icon_color: 'B7D364',
    border_color: '68B587',
    ring_color: 'ABD200',
    accent_color: '68B587',
  },
  gruvbox: {
    bg_color: '282828',
    title_color: 'FABD2F',
    text_color: 'EBDBB2',
    icon_color: 'FE8019',
    border_color: 'FABD2F',
    ring_color: 'FE8019',
    accent_color: 'FB4934',
  },
  tokyonight: {
    bg_color: '1A1B26',
    title_color: '7AA2F7',
    text_color: 'A9B1D6',
    icon_color: 'BB9AF7',
    border_color: '7AA2F7',
    ring_color: 'BB9AF7',
    accent_color: 'F7768E',
  },
  onedark: {
    bg_color: '282C34',
    title_color: '61AFEF',
    text_color: 'ABB2BF',
    icon_color: '98C379',
    border_color: '61AFEF',
    ring_color: '98C379',
    accent_color: 'E06C75',
  },
  cobalt: {
    bg_color: '193549',
    title_color: 'E683D9',
    text_color: 'FFFFFF',
    icon_color: '79CBE8',
    border_color: 'E683D9',
    ring_color: '79CBE8',
    accent_color: 'E683D9',
  },
  synthwave: {
    bg_color: '2B213A',
    title_color: 'E2E9EC',
    text_color: 'E5E9F0',
    icon_color: 'E2E9EC',
    border_color: 'FE4ECD',
    ring_color: 'FE4ECD',
    accent_color: 'FE4ECD',
  },
  highcontrast: {
    bg_color: '000000',
    title_color: 'FFFFFF',
    text_color: 'FFFFFF',
    icon_color: '00FF00',
    border_color: 'FFFFFF',
    ring_color: '00FF00',
    accent_color: 'FF0000',
  },
  dracula: {
    bg_color: '282A36',
    title_color: 'FF79C6',
    text_color: 'F8F8F2',
    icon_color: '8BE9FD',
    border_color: 'BD93F9',
    ring_color: '8BE9FD',
    accent_color: 'FF79C6',
  },
  prussian: {
    bg_color: '172F45',
    title_color: 'BDDFFF',
    text_color: '6E9EB9',
    icon_color: '38A0FF',
    border_color: 'BDDFFF',
    ring_color: '38A0FF',
    accent_color: 'BDDFFF',
  },
  monokai: {
    bg_color: '272822',
    title_color: 'F92672',
    text_color: 'F8F8F2',
    icon_color: 'A6E22E',
    border_color: 'F92672',
    ring_color: 'A6E22E',
    accent_color: 'FD971F',
  },
  vue: {
    bg_color: '273849',
    title_color: '42B883',
    text_color: 'EEEEEE',
    icon_color: '42B883',
    border_color: '42B883',
    ring_color: '42B883',
    accent_color: '35495E',
  },
  'vue-dark': {
    bg_color: '0F1418',
    title_color: '42D392',
    text_color: 'EEEEEE',
    icon_color: '42D392',
    border_color: '42D392',
    ring_color: '42D392',
    accent_color: '35495E',
  },
  'shades-of-purple': {
    bg_color: '2D2B55',
    title_color: 'FAD000',
    text_color: 'A599E9',
    icon_color: 'B362FF',
    border_color: 'FAD000',
    ring_color: 'B362FF',
    accent_color: 'FAD000',
  },
  nightowl: {
    bg_color: '011627',
    title_color: 'C792EA',
    text_color: '7FDBCA',
    icon_color: 'FFEB95',
    border_color: 'C792EA',
    ring_color: 'FFEB95',
    accent_color: 'C792EA',
  },
  buefy: {
    bg_color: '363636',
    title_color: '7957D5',
    text_color: 'FFFFFF',
    icon_color: 'FF3860',
    border_color: '7957D5',
    ring_color: 'FF3860',
    accent_color: '7957D5',
  },
  'blue-green': {
    bg_color: '040F0F',
    title_color: '00D9FF',
    text_color: 'C3E88D',
    icon_color: '00D9FF',
    border_color: '00D9FF',
    ring_color: 'C3E88D',
    accent_color: '00D9FF',
  },
  algolia: {
    bg_color: '050F2C',
    title_color: '00AEFF',
    text_color: 'FFFFFF',
    icon_color: '2DDE98',
    border_color: '00AEFF',
    ring_color: '2DDE98',
    accent_color: '00AEFF',
  },
  'great-gatsby': {
    bg_color: '000000',
    title_color: 'FFA726',
    text_color: 'FAFAFA',
    icon_color: '663399',
    border_color: 'FFA726',
    ring_color: '663399',
    accent_color: 'FFA726',
  },
  darcula: {
    bg_color: '2B2B2B',
    title_color: 'BA5F17',
    text_color: 'BABABA',
    icon_color: '529955',
    border_color: 'BA5F17',
    ring_color: '529955',
    accent_color: 'BA5F17',
  },
  bear: {
    bg_color: '1F2023',
    title_color: 'E03C8A',
    text_color: 'BCBABE',
    icon_color: '00AEFF',
    border_color: 'E03C8A',
    ring_color: '00AEFF',
    accent_color: 'E03C8A',
  },
  'solarized-dark': {
    bg_color: '002B36',
    title_color: '268BD2',
    text_color: '839496',
    icon_color: 'B58900',
    border_color: '268BD2',
    ring_color: 'B58900',
    accent_color: 'CB4B16',
  },
  'solarized-light': {
    bg_color: 'FDF6E3',
    title_color: '268BD2',
    text_color: '657B83',
    icon_color: 'B58900',
    border_color: '268BD2',
    ring_color: 'B58900',
    accent_color: 'CB4B16',
  },
  'chartreuse-dark': {
    bg_color: '000000',
    title_color: '7FFF00',
    text_color: 'FFFFFF',
    icon_color: '00AEFF',
    border_color: '7FFF00',
    ring_color: '00AEFF',
    accent_color: '7FFF00',
  },
  nord: {
    bg_color: '2E3440',
    title_color: '81A1C1',
    text_color: 'D8DEE9',
    icon_color: '88C0D0',
    border_color: '81A1C1',
    ring_color: '88C0D0',
    accent_color: 'BF616A',
  },
  gotham: {
    bg_color: '0C1014',
    title_color: '2AA889',
    text_color: '99D1CE',
    icon_color: '599CAB',
    border_color: '2AA889',
    ring_color: '599CAB',
    accent_color: 'C23127',
  },
  'material-palenight': {
    bg_color: '292D3E',
    title_color: 'C792EA',
    text_color: 'A6ACCD',
    icon_color: '89DDFF',
    border_color: 'C792EA',
    ring_color: '89DDFF',
    accent_color: 'F07178',
  },
  graywhite: {
    bg_color: 'FFFFFF',
    title_color: '24292E',
    text_color: '24292E',
    icon_color: '24292E',
    border_color: 'E1E4E8',
    ring_color: '0366D6',
    accent_color: '0366D6',
  },
  'vision-friendly-dark': {
    bg_color: '000000',
    title_color: 'FFFF00',
    text_color: 'FFFFFF',
    icon_color: 'FFFF00',
    border_color: 'FFFF00',
    ring_color: 'FFFF00',
    accent_color: 'FFFF00',
  },
  'ayu-mirage': {
    bg_color: '1F2430',
    title_color: 'F29E74',
    text_color: 'CBCCC6',
    icon_color: '73D0FF',
    border_color: 'F29E74',
    ring_color: '73D0FF',
    accent_color: 'F28779',
  },
  'midnight-purple': {
    bg_color: '000000',
    title_color: '9745F5',
    text_color: 'FFFFFF',
    icon_color: '9F4BFF',
    border_color: '9745F5',
    ring_color: '9F4BFF',
    accent_color: '9745F5',
  },
  calm: {
    bg_color: '1E2127',
    title_color: 'E07A5F',
    text_color: 'EBDBB2',
    icon_color: '81B29A',
    border_color: 'E07A5F',
    ring_color: '81B29A',
    accent_color: 'F2CC8F',
  },
  'flag-india': {
    bg_color: 'FFFFFF',
    title_color: 'FF8F1C',
    text_color: '250E62',
    icon_color: '138808',
    border_color: 'FF8F1C',
    ring_color: '138808',
    accent_color: '000080',
  },
  omni: {
    bg_color: '191622',
    title_color: 'FF79C6',
    text_color: 'E1E1E6',
    icon_color: 'E89E64',
    border_color: 'FF79C6',
    ring_color: 'E89E64',
    accent_color: '67E480',
  },
  react: {
    bg_color: '20232A',
    title_color: '61DAFB',
    text_color: 'FFFFFF',
    icon_color: '61DAFB',
    border_color: '61DAFB',
    ring_color: '61DAFB',
    accent_color: '61DAFB',
  },
  jolly: {
    bg_color: '291B3E',
    title_color: 'FF64DA',
    text_color: 'FFFFFF',
    icon_color: 'A960FF',
    border_color: 'FF64DA',
    ring_color: 'A960FF',
    accent_color: 'FFDD00',
  },
  maroongold: {
    bg_color: '260000',
    title_color: 'F7EF8A',
    text_color: 'F8F8F2',
    icon_color: 'E28905',
    border_color: 'F7EF8A',
    ring_color: 'E28905',
    accent_color: 'F7EF8A',
  },
  yeblu: {
    bg_color: '002046',
    title_color: 'FFFF00',
    text_color: 'FFFFFF',
    icon_color: '00FFFF',
    border_color: 'FFFF00',
    ring_color: '00FFFF',
    accent_color: 'FFFF00',
  },
  blueberry: {
    bg_color: '242938',
    title_color: '82AAFF',
    text_color: '27E8A7',
    icon_color: '89DDFF',
    border_color: '82AAFF',
    ring_color: '89DDFF',
    accent_color: 'FFCB8B',
  },
  slateorange: {
    bg_color: '36393F',
    title_color: 'E07856',
    text_color: 'FFFFFF',
    icon_color: 'E07856',
    border_color: 'E07856',
    ring_color: 'E07856',
    accent_color: 'E07856',
  },
  kacho_ga: {
    bg_color: 'BF4A3F',
    title_color: 'FFE09E',
    text_color: 'D9C8A9',
    icon_color: 'A64833',
    border_color: 'FFE09E',
    ring_color: 'A64833',
    accent_color: 'FFE09E',
  },
  outrun: {
    bg_color: '141439',
    title_color: 'FFCC00',
    text_color: '8B92D9',
    icon_color: 'FF1B6B',
    border_color: 'FFCC00',
    ring_color: 'FF1B6B',
    accent_color: 'FFCC00',
  },
  ocean_dark: {
    bg_color: '151A28',
    title_color: '8957B2',
    text_color: 'FFFFFF',
    icon_color: '00D9FF',
    border_color: '8957B2',
    ring_color: '00D9FF',
    accent_color: '8957B2',
  },
  city_lights: {
    bg_color: '1D252C',
    title_color: '5D8CB3',
    text_color: 'EBBF3E',
    icon_color: 'E27E8D',
    border_color: '5D8CB3',
    ring_color: 'E27E8D',
    accent_color: 'EBBF3E',
  },
  github_dark: {
    bg_color: '0D1117',
    title_color: '58A6FF',
    text_color: 'C9D1D9',
    icon_color: '1F6FEB',
    border_color: '30363D',
    ring_color: '58A6FF',
    accent_color: '58A6FF',
  },
  discord_old_blurple: {
    bg_color: '7289DA',
    title_color: 'FFFFFF',
    text_color: 'FFFFFF',
    icon_color: 'FFFFFF',
    border_color: 'FFFFFF',
    ring_color: 'FFFFFF',
    accent_color: 'FFFFFF',
  },
  aura_dark: {
    bg_color: '15141B',
    title_color: 'A277FF',
    text_color: 'EDECEE',
    icon_color: '61FFCA',
    border_color: 'A277FF',
    ring_color: '61FFCA',
    accent_color: 'FFCA85',
  },
  panda: {
    bg_color: '292A2B',
    title_color: 'FF75B5',
    text_color: 'F3F3F3',
    icon_color: '19F9D8',
    border_color: 'FF75B5',
    ring_color: '19F9D8',
    accent_color: 'FFB86C',
  },
  noctis_minimus: {
    bg_color: '1B2932',
    title_color: 'E3B341',
    text_color: 'FFFFFF',
    icon_color: '7ACCD7',
    border_color: 'E3B341',
    ring_color: '7ACCD7',
    accent_color: 'E3B341',
  },
  cobalt2: {
    bg_color: '193549',
    title_color: 'FFC600',
    text_color: 'FFFFFF',
    icon_color: '0088FF',
    border_color: 'FFC600',
    ring_color: '0088FF',
    accent_color: 'FFC600',
  },
  swift: {
    bg_color: 'F05138',
    title_color: 'FFFFFF',
    text_color: 'FFFFFF',
    icon_color: 'FFFFFF',
    border_color: 'FFFFFF',
    ring_color: 'FFFFFF',
    accent_color: 'FFFFFF',
  },
  aura: {
    bg_color: '15141B',
    title_color: 'A277FF',
    text_color: 'EDECEE',
    icon_color: '61FFCA',
    border_color: 'A277FF',
    ring_color: '61FFCA',
    accent_color: 'FFCA85',
  },
  apprentice: {
    bg_color: '262626',
    title_color: 'FFFFFF',
    text_color: 'BCBCBC',
    icon_color: '87AF87',
    border_color: 'FFFFFF',
    ring_color: '87AF87',
    accent_color: 'FFFFAF',
  },
  moltack: {
    bg_color: 'F4F4F5',
    title_color: '34495E',
    text_color: '333333',
    icon_color: '00D8FF',
    border_color: '34495E',
    ring_color: '00D8FF',
    accent_color: 'F39C12',
  },
  codeSTACKr: {
    bg_color: '1A1B27',
    title_color: 'FF652F',
    text_color: 'FFFFFF',
    icon_color: 'FFE400',
    border_color: 'FF652F',
    ring_color: 'FFE400',
    accent_color: '14C2A3',
  },
  rose_pine: {
    bg_color: '191724',
    title_color: 'EB6F92',
    text_color: 'E0DEF4',
    icon_color: '9CCFD8',
    border_color: 'EB6F92',
    ring_color: '9CCFD8',
    accent_color: 'F6C177',
  },
}

/**
 * Get theme with URL parameter overrides
 */
export function getTheme(
  themeName: string = 'default',
  customColors?: Partial<Theme>,
): Theme {
  const baseTheme = themes[themeName] || themes.default
  return { ...baseTheme, ...customColors }
}

/**
 * Convert hex to RGB for transparency effects
 */
export function hexToRgb(hex: string): { r: number; g: number; b: number } {
  const result = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex)
  return result
    ? {
        r: parseInt(result[1], 16),
        g: parseInt(result[2], 16),
        b: parseInt(result[3], 16),
      }
    : { r: 0, g: 0, b: 0 }
}
